#!/bin/bash

# Script to add test PostgreSQL instance via API
# This assumes you're already logged in to the UI

echo "==================================="
echo "Add Test PostgreSQL Instance"
echo "==================================="
echo ""
echo "Please follow these steps in your browser:"
echo ""
echo "1. Open your application: http://localhost:3000"
echo ""
echo "2. Navigate to: Instances page"
echo ""
echo "3. Click: 'Add PostgreSQL Instance' button"
echo ""
echo "4. Fill in the form with these details:"
echo "   ┌─────────────────────────────────────────────┐"
echo "   │ Name:     Test Database                     │"
echo "   │ Host:     rustfs-manager-test-db            │"
echo "   │ Port:     5432                              │"
echo "   │ Database: testdb                            │"
echo "   │ Username: testuser                          │"
echo "   │ Password: testpass123                       │"
echo "   └─────────────────────────────────────────────┘"
echo ""
echo "5. Click: 'Add Instance' or 'Save'"
echo ""
echo "==================================="
echo "Connection Details"
echo "==================================="
echo ""
echo "Container Name: rustfs-manager-test-db"
echo "Internal Host:  rustfs-manager-test-db"
echo "External Host:  localhost"
echo "Internal Port:  5432"
echo "External Port:  5000"
echo "Database:       testdb"
echo "Username:       testuser"
echo "Password:       testpass123"
echo ""
echo "==================================="
echo "Verify Container is Running"
echo "==================================="
docker ps | grep test-db
echo ""
echo "==================================="
echo "Test Connection (Optional)"
echo "==================================="
echo ""
echo "From host machine:"
echo "  psql -h localhost -p 5000 -U testuser -d testdb"
echo ""
echo "From inside container:"
echo "  docker exec -it rustfs-manager-test-db psql -U testuser -d testdb"
echo ""
echo "==================================="
echo "Important Notes"
echo "==================================="
echo ""
echo "• Use 'rustfs-manager-test-db' as host (containers communicate via Docker network)"
echo "• Use port 5432 (internal container port, not 5000)"
echo "• The backend container can reach the test DB via the Docker network"
echo "• Port 5000 is only for external access from your host machine"
echo ""
